-- Creating Table users.
CREATE TABLE users (
	id INT AUTO_INCREMENT,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	name VARCHAR(100) NOT NULL,
	mobile_no VARCHAR(20) UNIQUE NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id)
);
